version: '3.8'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "ostock_dev"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: codingkiddo/configserver:0.0.5-SNAPSHOT
    ports:
       - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
  licensingservice:
    image: codingkiddo/licensing-service:0.0.5-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: "http://configserver:8888"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database:5432/ostock_dev"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on: 
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge